version: '3'

services:
    database:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_HOST: 'database'
            MYSQL_DATABASE: 'reservations'
            MYSQL_USER: 'student'
            MYSQL_PASSWORD: 'student'
            MYSQL_ROOT_PASSWORD: 'student'

    component:
        restart: always
        build: './'
        depends_on:
            - 'database'
        ports:
            - '3007:3007'
        environment:
            DB_HOST: 'database'
            DB_PORT: '3306'
            DB_USER: 'student'
            DB_PASSWORD: 'student'
            DB_DATABASE: 'reservations'